import { useMemo, useCallback } from 'react';
import { Capability } from '../types/menuOntology';

// Static mapping from system/project role to the set of capabilities granted.
// This drives menu visibility (Layer 1), route guards (Layer 2),
// and action guards (Layer 3) uniformly.
const roleCapabilities: Record<string, Capability[]> = {
  SPONSOR: [
    'view_dashboard',
    'view_requirements',
    'view_backlog',
    'view_wbs',
    'view_phases',
    'view_kanban',
    'view_sprints',
    'view_issues',
    'view_tests',
    'view_deliverables',
    'view_decisions',
    'view_lineage',
    'view_reports',
    'view_pmo',
    'view_stats',
    'view_meetings',
    'view_notices',
    'view_rfp',
    'view_ai_assistant',
  ],
  PMO_HEAD: [
    'view_dashboard',
    'view_requirements',
    'manage_requirements',
    'view_backlog',
    'manage_backlog',
    'view_wbs',
    'manage_wbs',
    'view_phases',
    'manage_phases',
    'view_kanban',
    'view_sprints',
    'manage_sprints',
    'view_issues',
    'manage_issues',
    'view_tests',
    'view_deliverables',
    'approve_deliverable',
    'view_decisions',
    'manage_decisions',
    'view_lineage',
    'view_reports',
    'export_reports',
    'view_pmo',
    'view_stats',
    'view_meetings',
    'view_notices',
    'view_education',
    'view_projects',
    'manage_projects',
    'view_rfp',
    'manage_rfp',
    'view_parts',
    'manage_parts',
    'manage_part_members',
    'view_roles',
    'manage_roles',
    'view_users',
    'manage_users',
    'admin_project',
    'edit_project_accountability',
    'view_role_permission',
    'manage_delegations',
    'manage_capabilities',
    'audit_governance',
    'view_ai_assistant',
  ],
  PM: [
    'view_dashboard',
    'view_requirements',
    'manage_requirements',
    'view_backlog',
    'manage_backlog',
    'view_wbs',
    'manage_wbs',
    'view_phases',
    'manage_phases',
    'view_kanban',
    'manage_kanban',
    'view_sprints',
    'manage_sprints',
    'view_issues',
    'manage_issues',
    'view_tests',
    'manage_tests',
    'view_deliverables',
    'manage_deliverables',
    'approve_deliverable',
    'view_decisions',
    'manage_decisions',
    'view_lineage',
    'view_reports',
    'export_reports',
    'view_pmo',
    'view_stats',
    'view_meetings',
    'view_notices',
    'view_ai_assistant',
    'view_education',
    'view_projects',
    'manage_projects',
    'view_rfp',
    'manage_rfp',
    'view_parts',
    'manage_parts',
    'manage_part_members',
    'view_roles',
    'manage_roles',
    'admin_project',
    'edit_project_accountability',
    'view_role_permission',
    'manage_delegations',
    'manage_capabilities',
    'audit_governance',
  ],
  DEVELOPER: [
    'view_dashboard',
    'view_requirements',
    'view_backlog',
    'view_wbs',
    'view_phases',
    'view_kanban',
    'manage_kanban',
    'view_sprints',
    'view_my_work',
    'view_issues',
    'view_tests',
    'view_deliverables',
    'view_decisions',
    'view_lineage',
    'view_reports',
    'view_meetings',
    'view_notices',
    'view_ai_assistant',
    'view_education',
  ],
  QA: [
    'view_dashboard',
    'view_requirements',
    'view_backlog',
    'view_kanban',
    'manage_kanban',
    'view_sprints',
    'view_issues',
    'manage_issues',
    'view_tests',
    'manage_tests',
    'view_deliverables',
    'manage_deliverables',
    'view_lineage',
    'view_reports',
    'view_meetings',
    'view_notices',
    'view_ai_assistant',
    'view_education',
  ],
  BUSINESS_ANALYST: [
    'view_dashboard',
    'view_requirements',
    'manage_requirements',
    'view_backlog',
    'view_phases',
    'view_issues',
    'view_lineage',
    'view_reports',
    'view_stats',
    'view_meetings',
    'view_notices',
    'view_ai_assistant',
    'view_education',
    'view_rfp',
  ],
  AUDITOR: [
    'view_dashboard',
    'view_requirements',
    'view_phases',
    'view_deliverables',
    'view_lineage',
    'view_reports',
    'export_reports',
    'view_pmo',
    'view_stats',
    'export_audit_evidence',
    'view_notices',
  ],
  ADMIN: [
    'view_dashboard',
    'view_requirements',
    'manage_requirements',
    'view_backlog',
    'manage_backlog',
    'view_wbs',
    'manage_wbs',
    'view_phases',
    'manage_phases',
    'view_kanban',
    'manage_kanban',
    'view_sprints',
    'manage_sprints',
    'view_issues',
    'manage_issues',
    'view_tests',
    'manage_tests',
    'view_deliverables',
    'manage_deliverables',
    'approve_deliverable',
    'view_decisions',
    'manage_decisions',
    'view_lineage',
    'view_reports',
    'export_reports',
    'view_pmo',
    'view_stats',
    'view_my_work',
    'export_audit_evidence',
    'view_meetings',
    'view_notices',
    'view_ai_assistant',
    'view_education',
    'view_projects',
    'manage_projects',
    'view_rfp',
    'manage_rfp',
    'view_parts',
    'manage_parts',
    'manage_part_members',
    'view_roles',
    'manage_roles',
    'view_users',
    'manage_users',
    'admin_project',
    'admin_system',
    'edit_project_accountability',
    'view_role_permission',
    'manage_delegations',
    'manage_capabilities',
    'audit_governance',
  ],
};

/**
 * Provides capability-based access control for the current user.
 *
 * Capabilities are derived from the user's role and drive:
 *   - Menu visibility (MenuOntologyNode.requiredCaps)
 *   - Route guards (ProtectedRoute)
 *   - Action guards (<Can /> wrapper, drag-drop, approval buttons)
 *
 * @param userRole - The current user's role key (e.g. "PM", "DEVELOPER")
 */
export function useCapabilities(userRole: string) {
  const capabilities = useMemo(() => {
    return new Set<Capability>(roleCapabilities[userRole] || []);
  }, [userRole]);

  const hasCapability = useCallback(
    (cap: Capability) => capabilities.has(cap),
    [capabilities],
  );

  const hasAnyCapability = useCallback(
    (caps: Capability[]) => caps.some((c) => capabilities.has(c)),
    [capabilities],
  );

  const hasAllCapabilities = useCallback(
    (caps: Capability[]) => caps.every((c) => capabilities.has(c)),
    [capabilities],
  );

  return { capabilities, hasCapability, hasAnyCapability, hasAllCapabilities };
}
