import type { Role, Permission } from './types';

// Predefined role definitions
export const ROLES: Role[] = [
  {
    id: 'sponsor',
    name: '프로젝트 스폰서',
    nameEn: 'Project Sponsor',
    description: '프로젝트의 최종 의사결정, 예산 승인, 비즈니스 목표 설정',
    userCount: 2,
  },
  {
    id: 'pmo_head',
    name: 'PMO 총괄',
    nameEn: 'PMO Head',
    description: '전사 프로젝트 포트폴리오 관리, PMO 조직 운영',
    userCount: 1,
  },
  {
    id: 'pm',
    name: '프로젝트 관리자',
    nameEn: 'Project Manager',
    description: '개별 프로젝트의 계획, 실행, 통제, 종료 책임',
    userCount: 3,
  },
  {
    id: 'developer',
    name: '개발팀',
    nameEn: 'Development Team',
    description: '사용자 스토리 구현, 단위 테스트, 코드 개발',
    userCount: 12,
  },
  {
    id: 'qa',
    name: 'QA팀',
    nameEn: 'QA Team',
    description: '테스트 케이스 설계, 통합/시스템 테스트 수행',
    userCount: 4,
  },
  {
    id: 'business_analyst',
    name: '현업 분석가',
    nameEn: 'Business Analyst',
    description: '업무 요구사항 정의, PoC 결과 검증',
    userCount: 5,
  },
  {
    id: 'auditor',
    name: '외부 감리',
    nameEn: 'External Auditor',
    description: '프로젝트 진행 상황 및 산출물 제3자 검토',
    userCount: 2,
  },
  {
    id: 'admin',
    name: '시스템 관리자',
    nameEn: 'System Admin',
    description: '시스템 운영, 사용자 계정 및 권한 관리',
    userCount: 2,
  },
];

// Initial permission matrix
export const INITIAL_PERMISSIONS: Permission[] = [
  {
    id: 'view_dashboard',
    category: '대시보드',
    name: '전사 프로젝트 대시보드 조회',
    roles: {
      sponsor: true,
      pmo_head: true,
      pm: true,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: true,
      admin: false,
    },
  },
  {
    id: 'create_project',
    category: '프로젝트',
    name: '프로젝트 생성',
    roles: {
      sponsor: false,
      pmo_head: true,
      pm: true,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: true,
    },
  },
  {
    id: 'delete_project',
    category: '프로젝트',
    name: '프로젝트 삭제',
    roles: {
      sponsor: false,
      pmo_head: true,
      pm: false,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: true,
    },
  },
  {
    id: 'manage_wbs',
    category: '일정관리',
    name: 'WBS 작성 및 수정',
    roles: {
      sponsor: false,
      pmo_head: true,
      pm: true,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'manage_budget',
    category: '예산관리',
    name: '예산 편성 및 수정',
    roles: {
      sponsor: true,
      pmo_head: true,
      pm: false,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'approve_budget',
    category: '예산관리',
    name: '예산 최종 승인',
    roles: {
      sponsor: true,
      pmo_head: false,
      pm: false,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'manage_risk',
    category: '리스크/이슈',
    name: '리스크 및 이슈 등록/수정',
    roles: {
      sponsor: false,
      pmo_head: true,
      pm: true,
      developer: true,
      qa: true,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'approve_deliverable',
    category: '산출물',
    name: '산출물 승인/반려',
    roles: {
      sponsor: true,
      pmo_head: true,
      pm: true,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'manage_backlog',
    category: '애자일',
    name: '백로그 관리',
    roles: {
      sponsor: false,
      pmo_head: false,
      pm: true,
      developer: true,
      qa: true,
      business_analyst: true,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'manage_sprint',
    category: '애자일',
    name: '스프린트 관리',
    roles: {
      sponsor: false,
      pmo_head: false,
      pm: true,
      developer: true,
      qa: true,
      business_analyst: false,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'use_ai_assistant',
    category: 'AI 기능',
    name: 'AI 어시스턴트 사용',
    roles: {
      sponsor: true,
      pmo_head: true,
      pm: true,
      developer: true,
      qa: true,
      business_analyst: true,
      auditor: false,
      admin: false,
    },
  },
  {
    id: 'view_audit_log',
    category: '보안/감사',
    name: '감사 로그 조회',
    roles: {
      sponsor: false,
      pmo_head: true,
      pm: false,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: true,
      admin: true,
    },
  },
  {
    id: 'manage_users',
    category: '보안/감사',
    name: '사용자 및 권한 관리',
    roles: {
      sponsor: false,
      pmo_head: false,
      pm: false,
      developer: false,
      qa: false,
      business_analyst: false,
      auditor: false,
      admin: true,
    },
  },
];
