package com.insuretech.pms.report.entity;

/**
 * Report generation mode enumeration
 */
public enum GenerationMode {
    AUTO,   // Automatically generated by scheduler
    MANUAL  // Manually triggered by user
}
